title = "Abhishek Hodavdekar"
baseURL = "https://abhishekkh.github.io"
languageCode = "en-us"
theme = "ananke"

Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-177003439-1"
enableRobotsTXT = true
enableEmoji = true
enableInlineShortcodes = true


[params]
 favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://www.github.com/abhishekkh"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/abhishekkh/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = ""
  recent_posts_number = 2
  show_reading_time = true